
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: ui-build
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_AGENT_URL=http://backend:7777
      - NEXT_PUBLIC_TAVILY_API_KEY=${TAVILY_API_KEY}
      - NEXT_PUBLIC_GROQ_API_KEY=${GROQ_API_KEY}
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: agent
    ports:
      - "7777:7777"
    environment:
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
