name: Deploy agent-ui (Next.js) to Azure Web App - examenmodelado1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout
      id-token: write # Required for Azure login

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F10ADF9EFE4F4D1EA022F82F1B435A7C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0CD9D80E1ECC4A0F8D820D8DE1707928 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D6A6345C367E4781907E9E977384C76D }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'examenmodelado1'
          slot-name: 'Production'
          package: ./agent-ui
